### ISSUE TITLE
PL-400 Issues

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#1]
Practice Lab – Validate lab environment

This should be Next and not Save

![image](https://user-images.githubusercontent.com/41710326/105912314-e5f8a700-5ff0-11eb-9d11-8110aa48a8b1.png)

Lab 01 – Data Modeling | Exercise #2: Create Tables and Columns |  Task #5: Edit Status Reason Options | Step 3.  In class view, this is still "Entities" instead of Tables. 

![image](https://user-images.githubusercontent.com/41710326/105866443-9a76d680-5fb9-11eb-8698-af296c998124.png)

Same section, this is still "Fields" and not columns:

![image](https://user-images.githubusercontent.com/41710326/105867864-29d0b980-5fbb-11eb-9884-e53e5a461dff.png)

Step 11 as well:

![image](https://user-images.githubusercontent.com/41710326/105869359-c3e53180-5fbc-11eb-8736-e2d5da2ca695.png)

Lab 02 – Model driven app |  Task #1: Edit Permit Form and View | Step 2

There needs to be steps of how to find the Permit Type column to drag and drop. 

Lab 03 - Canvas App | Task #4: Add Inspection Details Screen |  Step 3.  This should be "Tree View" not "Three View". 

Same section, step 5 the name and scheduled date already exist. Instructions need to read to add Status Reason and Comments:

![image](https://user-images.githubusercontent.com/41710326/105929874-23b7f880-600e-11eb-99d1-d99783d110c0.png)

Step 6 should read you will see an error message:

![image](https://user-images.githubusercontent.com/41710326/105930091-988b3280-600e-11eb-94b2-94206aa722f3.png)

Lab 04 – Client Scripting |   Task #4: Test Event Handlers | Step 3

In two test runs, we consistently get the following with the on-load permit form (this is post-clear and refreshing):

![image](https://user-images.githubusercontent.com/41710326/106006815-3c122c80-607b-11eb-8b75-4f482bf711ac.png)

Lab 05 – Power Apps Component Framework | Exercise #1: Create the PCF Control | Task #2: Setup Components Project | Step 4 

A new command prompt needs to be opened before running the PAC commands:

![image](https://user-images.githubusercontent.com/41710326/106011316-f60b9780-607f-11eb-97fd-3dfdd20a4311.png)

Lab 05 – Power Apps Component Framework |  Exercise #2: Publish to Microsoft Dataverse |  Task #3: Debug 

F12 returned the following errors, making this task incompletable: 

![image](https://user-images.githubusercontent.com/41710326/106052034-c758e580-60ae-11eb-8e1c-1c9383a27895.png)

Lab 06 – Plug-ins |  Exercise #1: Block New Permit Creation Plugin | Task #1: Create the plugin | Step 1

Suggestion:   Add a note of which version of Visual Studio is in reference. 

Lab 06 – Plug-ins |  Exercise #1: Block New Permit Creation Plugin | Task #1: Create the plugin | Step 5 

Screenshot   does not display the the 'using' statements below the class. 'using'   statements should be included at the start of the program.

![image](https://user-images.githubusercontent.com/41710326/106052784-a2b13d80-60af-11eb-9c90-96cf49e9321b.png)

Lab 07 – Azure Functions |  Task #2: Create Application User and Security Role | Step 4

Full Name column is absent.  

Exercise #2: Create Azure Function for Inspection Routing |  Task #1: Create the Function |  Step 2 

The   below output is made, contradictory to the one present in the instructional   screenshot.
--

![image](https://user-images.githubusercontent.com/41710326/106053812-d6d92e00-60b0-11eb-9959-d44ad696bb85.png)

 Exercise #2: Create Azure Function for Inspection Routing |  Task #1: Create the Function |  Step 3 (9)

Add a   note at step 2(4) not to stop debugging else the below error will be present.
--

![image](https://user-images.githubusercontent.com/41710326/106054085-2cadd600-60b1-11eb-9c31-dbe994b12ba9.png)

Lab 9:

Suggestion to put all code blocks in a type/text |  code block. Example:

       ``` 
       private static Task<CRMGetListResult<ExpandoObject>> GetUsers(CRMWebAPI api)
        {
        var users = api.GetList<ExpandoObject>("systemusers");
        return users;
        }
       ```

Lab 9 | Exercise #3: Publish and Test | Task #1: Publish to Azure | Step 1

![image](https://user-images.githubusercontent.com/41710326/106055737-6b449000-60b3-11eb-8773-deca7cb9b672.png)

 

Due to   the error above, publishing seemed unaccomplishable Lab 07 was finished   prematurely and Lab 08 was continued.
--

Lab 08 – Publishing Events Externally | Exercise #1: Create an Azure Function |  Task #1: Create Azure Function App | Step 1 (4)

Creating   a new resource group requires a name.
--
![image](https://user-images.githubusercontent.com/41710326/106055976-b78fd000-60b3-11eb-8622-6173cf2546fa.png)

Exercise #2: Configure Web Hook |  Task #2: Create an Azure Function | Step 2 

Suggestion: 

Instructions   to observe past logs should be included. Instructions unclear.
--

Lab 09 – Custom Connector |  Exercise #3 Test Connector | Task #2: Test on Flow |  Step 4

Connection   must be recreated before step 4 can continue;
--

![image](https://user-images.githubusercontent.com/41710326/106056996-ed818400-60b4-11eb-90d4-4020cb6bcbbf.png)

 
Lab 10 – Application Lifecycle Management |  Exercise #3: Test the Pipeline |  Task #1: Run the Pipeline | Step 1 (12)

Run did   not execute successfully - 'Power Platform Export Solution' task failed to   connect to environment. See error below;
--

![image](https://user-images.githubusercontent.com/41710326/106057402-8b754e80-60b5-11eb-91ad-2c96ed7272fc.png)

Task #3: Run Build Pipeline |  Step 2 (6)  Jobs did not succeed due to above error. 

Step 3(3)  Due to earlier error reported 

![image](https://user-images.githubusercontent.com/41710326/106058400-cfb51e80-60b6-11eb-981b-23ae53b12123.png)

---------------

Suggestion/Ask: For the labs that have a majority of VS code entries, solution files be provided. That way if the end-user needs to compare what they may have done wrong, they can cross compare.

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update for this lab in the next couple of weeks.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
