### ISSUE TITLE
Lock Permit is not visible

### ISSUE THREAD

**Issue by vatanjoshi** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#10]
#### Step: 04 Lock Permit

Description of issue: Followed the instructions twice but seems the "Lock Permit" button is not visible.

1. Add Plugin Assembly and Plugin - step to the Permit Management solution
![image](https://user-images.githubusercontent.com/17869959/124069227-74b69780-da59-11eb-8a86-23eedb5ad252.png)
2. Check Enable Attachments and Notes,
![image](https://user-images.githubusercontent.com/17869959/124069293-8f890c00-da59-11eb-8f8d-a4c504ff42e0.png)
3. Set Enable Plugin Logging to Plugin Trace Log to All
![image](https://user-images.githubusercontent.com/17869959/124069343-a7609000-da59-11eb-881b-d946717252a1.png)
4. Create test record
![image](https://user-images.githubusercontent.com/17869959/124069488-e68ee100-da59-11eb-88b3-ccc092203f2b.png)
5. Lock permit is not visible 
![image](https://user-images.githubusercontent.com/17869959/124069548-fc040b00-da59-11eb-9cf1-4371f6ffeecb.png)

**Comment by DanePillay-nel** [comment]
Just make sure that you have added the button to the correct menu(There are three that appear in the Ribbon workbench) and that you have published.

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update for this lab in the next couple of weeks.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
