### ISSUE TITLE
Lab 0 Ex 2 Task 2.3: Not applicable after updated Task 2.2, navigation to 365 admin center needed

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#100]
- Practice Lab 0 - Validate lab environment
- Exercise 2 – Power Platform trial
- Task 2.3 – Assign Power Apps licenses to your user

Task 2.3, in which the Power Apps license previously obtained via the admin center is assigned to MOD Administrator, is not applicable following the update to Task 2.2 to provision a trial via https://powerapps.microsoft.com/ (897972445e7cca1ff9735626b3189ca5597fa2ff). After competing the updated Task 2.2, the Microsoft Power Apps Plan 2 Trial is already assigned to the MOD Administrator user. Removing Task 2.3 would prevent this mismatch.

Additionally, the updated Task 2.2 concludes with the make.powerapps.com tab open. Tasks 2.3 and 2.4 refer to actions within the 365 admin center page, without a preceding step indicating that the learner should navigate to the corresponding page. Adding a step at the end of Task 2.2 or the beginning of the next task would clarify this.

**Comment by julians1966** [comment]
Power Platform trials and setup steps have changed further
