### ISSUE TITLE
applied workshop solution is a managed solution

### ISSUE THREAD

**Issue by schuerstedt** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#109]
# Module: Applied Workshop solution
#### Step: 00

The new available applied workshop solution is a managed solution. Not really demo able as I cannot change anything. Can you upload a unmanaged solution? Although no description of the solution yet. 

Repro steps:

1.
1.
1.

**Comment by julians1966** [comment]
The PL-400T00A-ENU-TrainerDemoAssetsGuide pdf explains how to demo the sample solution

I use this to give students an idea as to what their finished solution might look like - I do not need to change it

**Comment by schuerstedt** [comment]
> The PL-400T00A-ENU-TrainerDemoAssetsGuide pdf explains how to demo the sample solution
> 
> I use this to give students an idea as to what their finished solution might look like - I do not need to change it

Hi Julian, I overlooked this file. I figured the application already. Would be nice to have the sources for the plugin etc. so. 

Thx for your reply. 

Marcus

**Comment by julians1966** [comment]
I don't have the code or unmanaged solution but will see if I can get them
