### ISSUE TITLE
Lab 10 - checking in into the GIT repo does not work

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#11]
Part of the Lab 10 - ALM is the check-in procedure for checking-in the unpacked Power Platform solution into the GIT repository in Azure DevOps. The procedure is implemented using a command line task in Azure DevOps. The steps are the following:

  echo commit all changes
  git config user.email "user@myorg.onmicrosoft.com"
  git config user.name "Automatic Build"
  git checkout master
  git add --all
  git commit -m "solution init"
  echo push code to new repo
  git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin master

There are actually 2 issues:
1. The steps must change the branch name "master" to "main", in alignment with the current functionality of Azure DevOps
2. Even after this change, the steps do not check - in anything into the GIT.  Here is the whole execution log:

Starting: Command Line Script
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\7a375376-b7d2-4f2f-b87c-cd69c088a938.cmd""
commit all changes
Switched to a new branch 'main'
Branch 'main' set up to track remote branch 'main' from 'origin'.
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
push code to new repo
Everything up-to-date
Finishing: Command Line Script

**Comment by RobertRybaric** [comment]
Solution can be found in the issue #2 from @wwherman 

You need to put always a BACKSLASH in the solution file specifications in the Azure DevOps tasks, like this:

**$(Build.ArtifactStagingDirectory)\$(SolutionName).zip**

**Comment by skulthm-ms** [comment]
Thank you Robert, we are releasing an update for this lab in the next couple of weeks. The solution you mentioned is merged now.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
