### ISSUE TITLE
Lab 11 - Minor issue with Function App

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#117]
# Lab 11 - Azure Functions
#### Step: 3

Description of issue

Part of the instructions in Step 3 are to pick .NET as the Runtime stack and "6 (LTS)" for the version.   In the Azure portal there is some confusion because there are two choices for version 6...  One is "6 (LTS) in-process" and the 2nd is "6 (LTS) Isolated."   It would be better to specify exactly which one the student should choose.

**Comment by julians1966** [comment]
Should be able to choose either, but would suggest Isolated as that will be the only option in the future

**Comment by skulthm-ms** [comment]
Thank you @tylerfarmer1. We will narrow it down in our next update.

**Comment by tylerfarmer1** [comment]
FYI - the "Isolated" one caused us issues in class.   Part of some of the labs have you edit some directly in the Azure portal.  One of the options - I *think* it was the in-process version - would show you the button to edit directly....but the other option would NOT show that button.
