### ISSUE TITLE
Ability to import components in Canvas apps is removed

### ISSUE THREAD

**Issue by FireyJoe** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#12]
# Lab/Demo: 03
#### Step: 4

Description of issue

The lab has you importing components. However, import has been deprecated and removed:
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/create-component. Users may be able to opt in for a limited time on a per-app basis. This portion of the lab will probably need redone.

Repro steps:

1. On Lab 3, Ex 1, Task 1, Step 4, there is no ellipses and no import option.

**Comment by ZekeStarr** [comment]
We have confirmed this issue at LODS as well.

**Comment by ChRocheFR** [comment]
Feature still present (I just tested it). All you need to do, is to go into App settings, and search for Import. This will allow you to enable the Export and Import Components option. The only problem is that it is a legacy option which will disappear in the future.

IMO, this is by far the smallest thing to correct in this course

**Comment by RobertRybaric** [comment]
@ChRocheFR : this is certainly not the smallest thing. I have recently found that issue and guided my students to create a label on the screens instead. For a newbie, this could be a show-stopper.

**Comment by Usamawahabkhan** [comment]
Please update the lab or remove it complately thanks

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update for this lab in the next couple of weeks. Please stay tuned.

**Comment by ChRocheFR** [comment]
I would like to add that the option is enabled by default now.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
