### ISSUE TITLE
Lab 11: Azure Function does not have +Create button any longer, so the lab steps are not do-able. 

### ISSUE THREAD

**Issue by Ellywati** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#121]
# Module: 
#### Step: 01 

Description of issue

Repro steps:

1. Exercise 3 Publish and Test 
2. This exercise was not working last week, as the app can not be published, the possibility of error is because the code is still using ADAL as opposed to MSAL. Either that or the Function app was under maintenance as the whole class could not create the http function as the +create button was not there anymore.

**Comment by julians1966** [comment]
I am not sure what you are saying exactly
1. Did you create the Function App in the portal in Exercise 2 and then select that Function App in Exercise 3?
2. Why could you not publish the function? Could you not select the Functon App or was the Publish button grayed out or did the publish fail with an error?
3. Which +Create button are you referring to?

**Comment by julians1966** [comment]
Yes, it worked for me back in early March when I last taught it. I am teaching PL-400 next week so I will go through the labs and see if I can figure this out. 
The ADAL library is out of support but still should publish.
Strange that you couldn't create a function from the portal - this looks like the root cause.
Did you have problems with Lab 12 as well?

**Comment by Ellywati** [comment]
Yes, I did have problems with subsequent labs (Lab 12 & 13) as none of the function apps work.
I am hoping it was only because Azure portal was having an update on Function App, so some functionality did not work as intended at that time.
Please let me know if you managed to make the labs work.

Thank you
________________________________

**Comment by julians1966** [comment]
Did you use an ALH lab environment? Did you use an Azure Pass or was a cloud slice setup for it?

**Comment by Ellywati** [comment]
I was using Learn on demand/Skillable lab, with Azure pass code provided in the lab environment

**Comment by julians1966** [comment]
I have seen a problem creating function apps in the lab using an Azure Pass. The error I am getting is that the subscription is forbidden from creating or updating the server farm

**Comment by julians1966** [comment]
My students are all getting this error.
Looking at support forums that this issue is widespread with many people with the same error, so it appears to be a Microsoft problem not a specific lab issue. 
This issue prevents labs 11,12, and 13 from being completed

**Comment by julians1966** [comment]
I am able to create function apps without getting the server farm error.

Select **6 (LTS), in-process model** for Version when creating the function app allows for Azure functions to be created from within the Azure portal
