### ISSUE TITLE
Lab 6 - Power Platform tools

### ISSUE THREAD

**Issue by chrzanowskiItta** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#122]
Exercise 2: Configuration Migration Tool
Task 2.1: Export data from Development
Step 23
I have export from crm failed. help !
![pl400issue1](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/26869408/6407b389-848d-49ad-9adb-a8c2dfcaa261)
![pl400issue2](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/26869408/a2b67125-7185-4df5-bf42-e850411360c2)

1.

**Comment by julians1966** [comment]
The UI and error log both show that you have no data in the Permit Type and Build Site tables
You need to create the 5 records in Lab 2 Task 2.2

**Comment by chrzanowskiItta** [comment]
thanks works !!
