### ISSUE TITLE
Lab 9 needs an update, many changes required for the PCF component to work - .ESLINTRC.JSON

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#124]
The file .eslintrc.json needs to be like this in order for the NPM BUILD to work:

{
    "env": {
      "browser": true,
      "es2020": true
    },
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/recommended"
    ],
    "globals": {
      "ComponentFramework": true
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
      "ecmaVersion": 12,
      "sourceType": "module"
    },
    "plugins": [
      "@microsoft/power-apps",
      "@typescript-eslint"
    ],
    "rules": {
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-var-requires": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "no-unused-vars": "off",
      "no-undef" : "off"
    }
}

**Comment by julians1966** [comment]
Checked and confirmed

**Comment by julians1966** [comment]
Closed by #140
