### ISSUE TITLE
Lab 9 needs an update, many changes required for the PCF component to work - CUSTOMIZATION

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#125]
In the customization for the table "Inspection", there is a status reason: "Cancelled" (double "l"), however in the TypeScript code for the PCF component the status reason is "Canceled" (sinle "l"), which is causing the yellow background color not to work. Need to consolidate these values.

**Comment by julians1966** [comment]
Tested and I see canceled inspections with yellow background
![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/29278645/1aba9409-1aef-4ae3-ac7d-2628a1a12c2a)
