### ISSUE TITLE
Lab 11 needs an update, many changes required for the solution to work

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#127]
Following are the required changes for the guidance description:

1. New screenshots for the security role settings, since the old UI does not exist anymore
2. Creating the Function App:

- Select "Consumption Plan" as the first selection for creating the function app
- Select ".NET 6 (LTS) in-process model"

3. Creating function in Visual Studio

- There is no .NET Core 3 (LTS) version anymore another must be selected
- After the Microsoft.IdentityModel.Clients.ActiveDirectory NuGet Package installed, the latest version of NetwonSoft.Json needs to be installed, otherwise the library from David Yack cannot be installed.
- Depending on the selected .NET version, various changes in code necessary

4. Deploying of the function in the cloud

- First, the setting on the Function App needs to be changed: SCM Basic Auth Publishing Credentials = ON
- The credentials are no more in "Configuration", but in "Environment variables"

5. Testing of the function
- CORS Settings need to include the Azure Portal URL

**Comment by tylerfarmer1** [comment]
I could really use help on this; I'm teaching the class this week, and this lab will be either June 13th or 14th, so if anyone has more updated instructions it would be much appreciated!!
