### ISSUE TITLE
Lab 01 - Exercise 01 - Task 02 - Step 04 - [Error] Deprecated

### ISSUE THREAD

**Issue by agilmstecs** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#13]
# Module: 00
#### Step: 04

When running the command pac pcf init --name timelinecontrol --namespace contoso --template dataset
Throws several errors:
![image](https://user-images.githubusercontent.com/41870381/128394974-e6280dbc-e54c-41c3-85e8-acae0d3d9db0.png)

If try to continue, when running command npm run build
Also throws several errors:
![image](https://user-images.githubusercontent.com/41870381/128395107-c988e86e-5438-43d7-ad74-e2cabcf0b503.png)

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update for this lab in the next couple of weeks.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
