### ISSUE TITLE
Lab 12 1.1 Azure portal Function all User Interface (UI) has changed and No longer matches instructions provided

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#130]
#### Step: 01

Description of issue:
- Azure portal Function all User Interface (UI) has changed and No longer matches instructions provided. Also, note that there is an alert of updating the application to a new runtime version for support since the version being used has been deprecated in 2022.

- The instructions state within the Functions tab "Select Create in Azure portal" and no option for AZ portal. 

![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/151560619/5b73a431-2383-4b81-b15a-2d9fcefb4490)

![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/151560619/dbb546ed-d4cc-45b7-872a-b1eee0d9e7ad)

**Comment by julians1966** [comment]
Selecting .NET 6 (LTS), in-process model  when creating the Azure Functionaapp, enables the Create in Azure Portal option.

![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/29278645/7db1fd8f-02c1-4ecb-a35d-3ae37333615e)
