### ISSUE TITLE
Lab 11 2.3 Screenshot of finished code doesnt match to the code Blocks of text being asked to enter

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#131]
#### Step: 04

Description of issue:

This is one instance of where the Code within the instructions for the user to paste within Visual Studio does NOT align with the screenshots provided. Multiple places within labs 7-10 as well have experienced issues like this. 

Code for student to enter:
![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/151560619/54dc8652-2417-4c7d-82d1-9fac38c663db)

Screenshot provided in instructions as solution following that step:
![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/151560619/bb4a59ad-6a08-4ab4-81f3-a5eafb7b96d9)

**Comment by julians1966** [comment]
Checked the Github repo 
https://microsoftlearning.github.io/PL-400_Microsoft-Power-Platform-Developer/Instructions/Labs/LAB%5BPL-400%5D_Lab11_Azure.html#exercise-2-create-azure-function-for-inspection-routing 
That screenshot is after step 6 and it looks correct there so it must be something in the ALH copy of the repo
