### ISSUE TITLE
Lab 3 1.4 Flip steps 3 and 4 to match the UI 

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#132]
#### Step: 03 & 04

Description of issue:
- To match the UI, steps 3 and 4 should switch. The first pop up is to select the data source which is in step 4 not 3.

**Comment by julians1966** [comment]
You don't have to select a data source in Step 3 after adding the form, selecting the Tree view tab automatically closes the popup 

This is how the lab was designed.
