### ISSUE TITLE
Lab 6 Task 4.2: Install .NET Framework in Visual Studio

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#133]
#### Step: 1

Description of issue:

When Visual Studio launched, it recommended an update to the user. This should be clarified whether an app update may be required or not by the user. This may also help with any other issues currently facing publishing to Azure. 

**
Please note as well, the step instructs to "Under Installation details pane, check .NET Framework 4.6.2 development tools." but there is no section of UI noticeable of *Installation Details*. VS does show when configuring that all installed workloads include .Net Framework 4.7.2. The only sign of developmental tools Individual components is 3.5.

**Comment by julians1966** [comment]
Updates should be applied

Can you confirm if using Visual Studio 2019 or Visual Studio 2022? Note: The instructions were written for VS 2019

**Comment by Skillable-Dev-Ap** [comment]
Confirmed VS19 being used.

**Comment by julians1966** [comment]
I presume this is Skillable as godeploy seem to have upgraded to Windows 11/VS 2022.
I need to check what the correct VM config should be.
If you apply updates to Visual Studio, you should then see Installation details pane on the right-hand side.

**Comment by julians1966** [comment]
I presume this is Skillable as godeploy seem to have upgraded to Windows 11/VS 2022
I need to check what the correct VM config should be
If you apply updates to Visual Studio, you should then see Installation details pane on the right-hand side
I will test when I get access to Skillable labs

**Comment by julians1966** [comment]
Skillable VM uses VS 2022

**Comment by Skillable-Dev-Ap** [comment]
Skillable VM contains VS 2022 and 2019. VS 2022 wasn't used while In testing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Skillable-Dev-Ap** [comment]
![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/151560619/5d8d2f93-4f7a-470a-96a0-721ffbd99626)

**Comment by julians1966** [comment]
Lab steps have been updated to include instructions to update Visual Studio
