### ISSUE TITLE
Lab 10 Task 3.2 step 2 - No Cancellations shown in Inspections Tab

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#134]
#### Step: 02

Description of issue:

Was able to successfully complete this lab but nothing populates within the inspections tab after locking the test permit. Expected outcome is two canceled inspections.

**Comment by julians1966** [comment]
You need to make sure you created the inspections in the earlier labs and set their status reasons. There should be 4 inspections in total for the Test Permit.
Inspections are not created in this lab, but 2 of the existing inspections have their status reason set to Canceled

**Comment by Skillable-Dev-Ap** [comment]
There were 4 created previously, but never reflected the updated status reason.

**Comment by julians1966** [comment]
Retested and 2 inspections were updated to canceled
