### ISSUE TITLE
Lab 11 Task 2.1 Version End Of Life 11/11/24

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#136]
#### Step: 03

Description of issue:

- Instructions:
- 
![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/151560619/c5fb3514-ae7a-497d-9c3f-b390a30c6b00)

There are two different versions of 6 LTS (Isolated worker Model and Process Model). Also of that when selecting either version 6, you receive an alert stating that .NET 6 version will reach EOL 11/11/24

**Comment by julians1966** [comment]
Either models will work.
The Dataverse Client SDK uses .NET 6.0.
Need to test if can use .NET 8.0

**Comment by julians1966** [comment]
Need to select **6 (LTS), in-process model** as the Dataverse Client SDK uses .NET 6.0.
