### ISSUE TITLE
Lab Setup File For CLOUD SLICE version of PL-400

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#138]
### Task: 3.2

Description of issue:

To cloud slice PL-400, Within the Lab Setup file, the instructions to redeem an Azure Pass should be removed.

I do recommend creating a 2nd Lab Setup file for the Cloud Slice versions of the lab (Labs 10-13) which needs contains the instructions for importing the solutions needed from Power Apps AFTER task 3.2 of creating the Live environment. The user will need to:

1. go to power apps
2. Select their dev environment
3. Go to Solutions and select Permit Manager Solution
4. Import solutions on the overview bar on the top of the page

Solutions import has already been tested to work successfully.

NOTE: The instructions for AZ Pass needs to be removed all together. The steps needed to import solutions should be on a copy of the Lab set up files that will be used only for the CS'd labs. naming would look something like: 

LAB[PL-400]_Lab00_Validate_lab_environment_CloudSlice.md

**Comment by julians1966** [comment]
The lab instructions are used by multiple lab hosters.
Not all of them have moved away from Azure Passes as far as I am aware.
If one ALH has implemented a different approach to the Azure subscription, it should be up to them to amend the instructions for their lab environments only
