### ISSUE TITLE
Lab 7 Task 1.2 Entities.cs empty

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#139]
# Module: 6
#### Step: 7

Description of issue

The generation of Entities.cs step fails with 
System.ArgumentException: An item with the same key has already been added

Workaround:
In Task 1.3 use the permitconsole - late bound.cs file in C:\LabFiles\L07\Resources instead of the early bound classes

**Comment by mhykgyver** [comment]
Hi Julian,

We tried using said late bound CS file but we encountered an error as per screenshot:

![Kevin error](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/12806459/9cc571b4-8cb5-4f76-b903-0d779e0a3f5e)

I took this screenshot from one of my students,  the connection string is looks ok and complete but we still get above error... any help is greatly appreciated...

**Comment by julians1966** [comment]
My class used this yesterday and it worked OK.
Is there a semi-colon in the password? If so put a single quote around the password

The AppId does not need to be changed, this is a special app registration that Microsoft provides for testing
