### ISSUE TITLE
Lab 5 -Power Apps Component Framework

### ISSUE THREAD

**Issue by DanePillay-nel** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#14]
# Module: 05
#### Step: 07

Description of issue: You will receive a bunch or errors about code being deprecated.

Repro steps:

1.When you run : npm run build

Solution so far requires the following to be run first.
npm link typescript
then npm run build

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update for this lab in the next couple of weeks.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
