### ISSUE TITLE
Lab 11 : Getting errors after test and Run steps. Owner column in Permit Inspection application is not changing

### ISSUE THREAD

**Issue by Pranjali-9999** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#149]
# Module: 11
### Task:
 Task 3.2: Test
#### Step: 3 Run the function.
Select Test/Run.

after selecting this , log file is giving errors for client id and , secret Id even though it is correct only. I have checked it twice.

I am attaching screenshots for more clarity
![Screenshot 2024-07-15 120820](https://github.com/user-attachments/assets/775a0904-ef0a-43b6-90b0-be36304beb2e)

Repro steps:

1.
1.
1.

**Comment by julians1966** [comment]
The lab steps worked OK two weeks ago when I delivered this course
You need to provide more details of the error as there is not enough to diagnose the issue from your screenshot

**Comment by InstrovateSakshi250399** [comment]
Even I am facing the same issue.

**Comment by julians1966** [comment]
This lab is removed in August 2024 Lab Update PR #150
