### ISSUE TITLE
.NET Framework versions conflict in Lab 11

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#151]
Lab 11 - There is no such value as ".NET Framework Isolated v4" in Visual Studio 2022:

![image](https://github.com/user-attachments/assets/01a347f6-04d8-4ce3-938f-98e625f0b8bb)

Currently the only values provided are according to the following picture:
![image](https://github.com/user-attachments/assets/ef2d4fb5-227f-462f-8e35-c87e81559e0b)

Since in the Function App we are using the LTS type, we must select the same here, which is ".NET 6.0 (Support ends November 12, 2024)"

**Comment by julians1966** [comment]
This lab is removed in August 2024 update #150
