### ISSUE TITLE
Extra closing curly bracket (}) in the code (Module 05)

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#155]
# Module: 05
#### Step: 03

**Description of issue:**
There’s an **extra closing curly bracket (})** in the code snippet after retrieving the inspections, which is causing a syntax error.

**Screenshot attached:**
![image](https://github.com/user-attachments/assets/5ba76335-ca0f-4815-985e-118edbea39df)

**Comment by julians1966** [comment]
OK will fix

**Comment by KashifKhaan** [comment]
Thanks for the quick fix!
