### ISSUE TITLE
Lab 9 missing from web site

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#156]
I see Lab 9 in GitHub, but it's not visible on https://microsoftlearning.github.io/PL-400_Microsoft-Power-Platform-Developer, which stops at Lab 8.   

It might be a YAML issue;  When you open the file directly in GitHub (the file called LAB[PL-400]_Lab09_Azure.md) you get an error message at the top:

Error in user YAML: (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 3 column 13

![image](https://github.com/user-attachments/assets/466b960f-5928-4a5f-9408-a162f386d916)

**Comment by julians1966** [comment]
Yes, it is a weird one and I can't figure out why

**Comment by julians1966** [comment]
Will look into this tomorrow

**Comment by julians1966** [comment]
Issue was extra quote on lab heading
Lab appears now in https://microsoftlearning.github.io/PL-400_Microsoft-Power-Platform-Developer/ 
Completed by PR #157
