### ISSUE TITLE
Missing Instructions for Azure Storage Resource Creation in Module 09, Lab 09, Task 5.1

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#158]
# Module: 09
#### Step: 01/Instruction: 14

Description of issue:
The instruction mentions that a storage resource was already created in a previous lab. However, there is no previous lab that involves the use of Azure or the creation of a storage resource. This creates confusion about how to proceed with the current task.

Please provide clarification on how to create the required storage resource or update the lab instructions accordingly to include the necessary steps.

**Attached Screenshot:**

![image](https://github.com/user-attachments/assets/6981905c-9ee9-45bf-8951-f77be5de3b55)

**Comment by julians1966** [comment]
1. Create Storage account.
   - Select **Show portal menu** and then select **+ Create a resource**.
   - Search for `storage account` and select **Storage account** by Microsoft.
   - Click on the **Storage account** tile.
   - Select **Create**.
   - Select your subscription.
   - Select the **PL400** for resource group.
   - Enter `pl400sa` followed by a unique number for Storage account name.
   - Select **Standard** for Performance.
   - Select **Locally-redundant storage (LRS)** for Redundancy.
   - Select **Review + create**.
   - Select **Create**.

**Comment by KashifKhaan** [comment]
Appreciated! Thank you for the prompt response!
