### ISSUE TITLE
Course screenshots old/obsolete: Specific recommendations for new screenshots in Lab 1 & 2

### ISSUE THREAD

**Issue by MOC-Labs-Review** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#16]
# Module: 00
#### Step: (various)

Description of issue

- General recommendation to update screenshots throughout the course so as to show current terminology and features.  Specific (high value) recommendations for screenshot updates here:

Lab 1, Exercise 1, Task 2, Step 2 -- Screen shot of publisher needs updating
Lab 1, Exercise 2, Task 1, Step 2 -- Screen shot needs updating to read Table
Lab 1, Exercise 2, Task 1, Step 3 -- Screen shot needs updating to read Columns	
Lab 2, Exercise 1, Task 1, Steps 2-6 & 10 -- Update screenshots to current version. Old screenshots showing old terminology and features
Lab 2, Exercise 1, Task 3, Steps 2 & 10 -- Update screenshots to current version. Old screenshots showing old terminology and features
Lab 2, Exercise 2, Task 2, Steps 2 & 5 -- Update screenshots to current version. Old screenshots showing old terminology and features

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review confirms this Issue per the latest review.

**Comment by skulthm-ms** [comment]
Thank you. We are releasing an update in the next couple of weeks.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
