### ISSUE TITLE
Error While Importing PermitManagement_1.0.0.0.zip: Version Conflict (Lab 09)

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#160]
# Module: 09
#### Step: 05

**Description of issue:**
I'm encountering the following issue: "**_The import solution must have a higher version than the existing solution it is upgrading_**" while attempting to import the **_PermitManagement_1.0.0.0.zip_** file. I have completed all the previous labs without any issues. Could you please provide a solution for this, and explain why this issue is occurring?

**Attached Screenshot:**
![image](https://github.com/user-attachments/assets/d79e3d50-e29a-4f5f-bf51-3fa6bba12b5f)

**Comment by julians1966** [comment]
Are you using an Azure Pass or are you starting another VM with an Azure Subscription. Currently both methods are supported but Azure Passes will be removed in the next few weeks
If you are simply continuing from the previous lab then there is this instruction
**If you are not using cloud slice and already have the solution installed you should skip to Exercise 4.**

**Comment by KashifKhaan** [comment]
I'm continuing from the previous lab, I'll perform the lab further by skipping to exercise 4.
Thank You!
