### ISSUE TITLE
Lab 09 - No Function URL copied in Ex 01

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#161]
# Module: 09
#### Step: 02

**Description of issue:**
Can you please verify this, there's no **Function URL** copied in **Ex 01**, it was previously copied in **Ex 07, Task 7.1, Step 12** and **Ex 05, Task 5.3,  Step 05**.

**Attached Screenshot:**

![image](https://github.com/user-attachments/assets/862c18e5-3d42-46e5-8217-86c9735b75b5)

**Comment by julians1966** [comment]
It should be in the Functional URL from Task 7.1

**Comment by KashifKhaan** [comment]
Thanks for the clarification!
