### ISSUE TITLE
Lab 09 - Incorrect Instructions

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#163]
# Module: 09
#### Step: 11

**Description of issue:**
This is supposed to be '**_Navigate to the Main Screen_**' not the **CPM Calc Screen** because the **CPM Button** is located in the **Main Screen**.

**Attached Screenshot:**
![image](https://github.com/user-attachments/assets/59784c74-ae62-4e9f-a1ca-c7447c489ced)

**Comment by julians1966** [comment]
No, this is a misunderstanding, the task describes what the steps underneath do which is to navigate from the Main Screen to the CPM Calc Screen

**Comment by KashifKhaan** [comment]
Ohh! Yes, got it.
Thanks for Clarification!
