### ISSUE TITLE
Lab 07 - Missing Instructions

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#168]
# Module: 07
#### Step: 07

**Description of issue:**
There should be an additional step _**Save & Close**_ after Changing the **Status Reason to New Request**. This step is necessary for the user to be able to see all four inspections.

**Attached Screenshot:**

![image](https://github.com/user-attachments/assets/5e2dee61-2799-4610-bab5-60d6eca9c967)

**Comment by skulthm-ms** [comment]
Step is added

**Comment by KashifKhaan** [comment]
Thank You!
