### ISSUE TITLE
getting errors when running msbuild /t:build /restore

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#172]
# Module: 07
#### Step: 03

Description of issue: getting errors when running `msbuild /t:build /restore`

Repro steps:

1. run up to task 1.3 step 3

![image](https://github.com/user-attachments/assets/43f5796d-640d-48fa-844f-c980a0a24afc)

**Comment by julians1966** [comment]
Check your .eslintrc.json against https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/blob/master/Allfiles/Labs/L07/Resources/.eslintrc.json

**Comment by julians1966** [comment]
Not able to recreate on my computer
Will test within an ALH lab instance

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. We will update on this soon. Thank you for your patience.

**Comment by julians1966** [comment]
Fixed by #179
