### ISSUE TITLE
Lab 7 - NPM run build failing

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#174]
#### Step: 11

Description of issue

npm run build is failing after making visual studio code changes as per the guide, see screenshot for error: 
![image](https://github.com/user-attachments/assets/3bed66ba-7d53-4d2c-837e-69326587d5da)

Edited the .ESLINTRC.JSON file to include the below as per this issue raised a while ago: https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/issues/124 

"rules": {
"@typescript-eslint/no-unused-vars": "off",
"@typescript-eslint/no-var-requires": "off",
"@typescript-eslint/no-explicit-any": "off",
"no-unused-vars": "off",
"no-undef" : "off"

Received a different error this time: 
![image](https://github.com/user-attachments/assets/4fd30d3b-2627-4374-987f-87cb45f7926f)

Lab 7 doesn't seem to work following the guide

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. We will update on this soon. Thank you for your patience.

**Comment by julians1966** [comment]
Ficed by #179
