### ISSUE TITLE
Practice Lab 7 – Power Apps Component Framework

### ISSUE THREAD

**Issue by fabricemct** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#177]
Practice Lab 7 – Power Apps Component Framework
Build and start

Run the following command in the Visual Studio Code Terminal window.

npm run build
i have this error
![image](https://github.com/user-attachments/assets/245bb022-1395-424a-9186-3e2a81b221d3)

**Comment by julians1966** [comment]
Thanks, will test it next week

**Comment by miberr** [comment]
I can verify that @kmtrading fix works. I'll PR tomorrow with additional fixes.

**Comment by julians1966** [comment]
Need to do this on a separate PR
