### ISSUE TITLE
Proper Client Script development workflow

### ISSUE THREAD

**Issue by miberr** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#178]
Hi all, I just had day 2 of this training and I demoed how to continuously edit and test scripts without updating the web resource. I had an idea that it would be cool to include this workflow in the instructions as well. I suggest using browser development tools instead of 3rd party software (Fiddler). 

If you think that would be a good idea, I can refactor the instructions and create PR. I'm already in progress of fixing issues and updating pictures so it would be no trouble 😊

**Comment by julians1966** [comment]
We are following Microsoft documentation https://learn.microsoft.com/en-us/power-apps/developer/model-driven-apps/streamline-javascript-development-fiddler-autoresponder as this is the recommended option
Although looking at this page, it is a little out of date

**Comment by julians1966** [comment]
Will monitor Docs to see if this changes
