### ISSUE TITLE
Storage account cant be selected

### ISSUE THREAD

**Issue by miberr** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#180]
#### Step: 1

With at least GoDeploy hosted labs, the previously created storage account cannot be selected. There is a quota set in the tenant that forces function to be created in Canada Central, while the storage account was created in East US by default (not specified in instructions). Will need either modifications to the tenant or to the instructions. If manually setting the region into East US, the following error is shown:

```json
{
    "code": "InvalidTemplateDeployment",
    "details": [
        {
            "code": "ValidationForResourceFailed",
            "message": "Validation failed for a resource. Check 'Error.Details[0]' for more information.",
            "details": [
                {
                    "code": "SubscriptionIsOverQuotaForSku",
                    "message": "This region has quota of 0 instances for your subscription. Try selecting different region or SKU."
                }
            ]
        }
    ],
    "message": "The template deployment 'Microsoft.Web-FunctionApp-Portal-da1c8df6-8039' is not valid according to the validation procedure. The tracking id is '167c8fa5-0428-41de-905c-c411a7873bbc'. See inner errors for details."
}
```

**Comment by julians1966** [comment]
Have you raised this with godeploy support?

**Comment by miberr** [comment]
Not yet, will do

**Comment by julians1966** [comment]
The labs state to create the storage account and function app in East US 2. I do not get an error when following the lab steps.
