### ISSUE TITLE
Azure function logging can't be done without application insights

### ISSUE THREAD

**Issue by miberr** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#181]
#### Step: 1

Logs can't be viewed without creating Application Insights instance first. Instructions needed to do this. Also it seems that creation of these additional resources has been prevented.

![image](https://github.com/user-attachments/assets/6041c495-9fd5-4149-878c-29c841b3af72)

**Comment by julians1966** [comment]
Application insights is available in Skillable, so this need to be raised with godeploy

**Comment by julians1966** [comment]
Application Insights Logs are far superior to be able to see the context, so app insights logs should be used
