### ISSUE TITLE
Practice Lab 4 - Power Platform tools - Issue

### ISSUE THREAD

**Issue by SkillableKA** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#184]
Microsoft Power Platform Developer
Practice Lab 4 - Power Platform tools
Exercise 1: Configuration Migration Tool
Task 1.2: Import data to Production
Step 13.) Select Import data

When running Step 13 to Import Data, it fails due to a Schema Validation error for missing entities. [P1-P2]

[P1]

![image](https://github.com/user-attachments/assets/06cf1d4a-b45f-4280-a66d-eea52c97db4f)

[P2]

![image](https://github.com/user-attachments/assets/c988577b-4095-4d2e-a1a8-df8a5ca3413d)

**Comment by julians1966** [comment]
This is because you didn't complete **Exercise 4: Export and import solution** in the previous lab, Lab 3.

**Comment by SkillableKA** [comment]
Thanks @julians1966 

I can confirm this resolved the instructor's issues. 

![image](https://github.com/user-attachments/assets/0bfff340-a57d-4982-a1d9-631a75b574b0)
