### ISSUE TITLE
LAB 4 - Ribbon Workbench

### ISSUE THREAD

**Issue by ngeorgeault** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#19]
# Module: 00
#### Step: 02

Description of issue
The new version of Ribbon Workbench does not allow to load a solution with more than 5 tables to improve loading performance.
You are have to create a temporary solution and add the table "Permit" in order to fulfill the workbench loading requirement (limitations).
Repro steps:
Try to execute Ribbon Workbench but depending on the version and especially if you are using the 3.1.443.1, you will not be able to open the solution "Permit Solution" because of the number of tables in your solution.
You will have to create a temporary solution, add the existing table "Permit", Publish all customizations and get back to ribbon Workbench to open your temporary solution.

As you are customizing the commands associated with the "Permit" Table, these customization will apply to all solutions where this table will be used and your command will finally correctly display in the "Permit Management" Solution and Model-Driven app.

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update in the next couple of weeks. Please stay tuned.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
