### ISSUE TITLE
PL-400 Errors and Remedies

### ISSUE THREAD

**Issue by wwherman** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#2]
There are literally hundreds and hundreds of grammatical, typographical, and graphical errors in the lab files. This results in confusion where code snippets and instructions don't match graphics which don't match the PowerApps and Azure sites. MCT's should expect a large time investment validating the lab instructions and files. I was able to fix every lab except Module 7.

Stumbling points:
Lab 4, Exercise 1, Task 4, Test Event Handlers - I received the same warnings and errors as described by mreherefortea but they did not prevent me from using the debugging tools and receiving the expected outcome. Filtered out warnings and errors to remove the distraction.

Lab 4, Exercise 2, Task 1, Step 3 - var permitType = formContext.getColumn("contoso_permittype").getValue(); should be var permitType = formContext.getAttribute("contoso_permittype").getValue(); 

Lab 4, Exercise 4, Task 4 - doesn't work and hasn't worked for years as it's described in the course. If you can't complete Lab 4 expect Lab 6 to also fail. Use this reference to fix the nonworking steps in the lab: https://ribbonworkbench.uservoice.com/knowledgebase/articles/169819-speed-up-publishing-of-solutions 

Lab 5, Exercise 1, Task 1 - a Visual Studio installation is required for this and future labs (no, it's not listed as necessary software for the course but should be). There are screenshots reflecting a Visual Studio 2019 installation but later course artifacts indicate Visual Studio 2017 was used, therefore, completed lab files will not work unless you have both 2017 and 2019 installed. Developer Command Prompt is used in this lab and Visual Studio will be used to create plug-ins in Chapter 6.

Lab 5, Exercise 1, Task 5, Step 1 - Ensure the styles are added to src\timelinecontrol\css\timelinecontrol.css and not out\controls\... or the styles will be overwritten on each run (the styles will work once and then the empty css will overwrite the defined styles in \out). This took a few debugging sessions to figure out.

Lab 7, Exercise 1, Task 2 - Couldn't complete Task 2 so lab was a bust for me. Tried numerous workarounds and found no joy. Moved on to Module 8.    

Lab 9, Exercise 3, Task 2, Step 2 - Add, Flow is no longer an option for the Power Apps Solution (options: Cloud flow, Desktop flow, and Dataflow). Select Cloud Flow, a new browser tab opens in Flow for editing, connect to the CPM Calculator, and then add values for text boxes. Guided instructions and screenshots are incorrect. 

Lab 10, Exercise 2, Task 1, Step 12 - command-line script is wrong and will not build and run (returns error: pathspec 'master' did not match any file(s) known to git). Use something like this instead (replacing my admin name and email with yours for the project):
git config user.email "wesley@protechinstructor.onmicrosoft.com"
git config user.name "wesley"
git checkout main
git add --all
git commit -a -m "solution init"
git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin main

You can download my corrected instructions here: https://1drv.ms/u/s!Ajc7F05xVXXpu3aT-5TMpPePYYSG

**Comment by v22arvind** [comment]
> There are literally hundreds and hundreds of grammatical, typographical, and graphical errors in the lab files. This results in confusion where code snippets and instructions don't match graphics which don't match the PowerApps and Azure sites. MCT's should expect a large time investment validating the lab instructions and files. I was able to fix every lab except Module 7.
> 
> Stumbling points:
> Lab 4, Exercise 1, Task 4, Test Event Handlers - I received the same warnings and errors as described by mreherefortea but they did not prevent me from using the debugging tools and receiving the expected outcome. Filtered out warnings and errors to remove the distraction.
> 
> Lab 4, Exercise 2, Task 1, Step 3 - var permitType = formContext.getColumn("contoso_permittype").getValue(); should be var permitType = formContext.getAttribute("contoso_permittype").getValue();
> 
> Lab 4, Exercise 4, Task 4 - doesn't work and hasn't worked for years as it's described in the course. If you can't complete Lab 4 expect Lab 6 to also fail. Use this reference to fix the nonworking steps in the lab: https://ribbonworkbench.uservoice.com/knowledgebase/articles/169819-speed-up-publishing-of-solutions
> 
> Lab 5, Exercise 1, Task 1 - a Visual Studio installation is required for this and future labs (no, it's not listed as necessary software for the course but should be). There are screenshots reflecting a Visual Studio 2019 installation but later course artifacts indicate Visual Studio 2017 was used, therefore, completed lab files will not work unless you have both 2017 and 2019 installed. Developer Command Prompt is used in this lab and Visual Studio will be used to create plug-ins in Chapter 6.
> 
> Lab 5, Exercise 1, Task 5, Step 1 - Ensure the styles are added to src\timelinecontrol\css\timelinecontrol.css and not out\controls... or the styles will be overwritten on each run (the styles will work once and then the empty css will overwrite the defined styles in \out). This took a few debugging sessions to figure out.
> 
> Lab 7, Exercise 1, Task 2 - Couldn't complete Task 2 so lab was a bust for me. Tried numerous workarounds and found no joy. Moved on to Module 8.
> 
> Lab 9, Exercise 3, Task 2, Step 2 - Add, Flow is no longer an option for the Power Apps Solution (options: Cloud flow, Desktop flow, and Dataflow). Select Cloud Flow, a new browser tab opens in Flow for editing, connect to the CPM Calculator, and then add values for text boxes. Guided instructions and screenshots are incorrect.
> 
> Lab 10, Exercise 2, Task 1, Step 12 - command-line script is wrong and will not build and run (returns error: pathspec 'master' did not match any file(s) known to git). Use something like this instead (replacing my admin name and email with yours for the project):
> git config user.email "[wesley@protechinstructor.onmicrosoft.com](mailto:wesley@protechinstructor.onmicrosoft.com)"
> git config user.name "wesley"
> git checkout main
> git add --all
> git commit -a -m "solution init"
> git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin main
> 
> You can download my corrected instructions here: https://1drv.ms/u/s!Ajc7F05xVXXpu3aT-5TMpPePYYSG

wow - why don't you create a pull request with all the fixes/corrections? it would be really helpful

**Comment by wwherman** [comment]
Because I don't get paid to write or update the course. I was only providing direction for other MCT's who try to deliver the course and can't figure out how to make the labs work.







________________________________

**Comment by DanePillay-nel** [comment]
**Lab 7, Exercise 1, Task 2 - Couldn't complete Task 2 so lab was a bust for me. Tried numerous workarounds and found no joy. Moved on to Module 8.**

So If you access the Advanced Settings from CE it works.
Not exactly like the lab.

All you need to do is enter the **app id** click save. It generates the rest of the details.

![image](https://user-images.githubusercontent.com/13525534/114923638-5c0ced00-9e2d-11eb-83e0-fa8faac41bc9.png)

**Comment by DanePillay-nel** [comment]
Code for Module 7

InspectionRouter.cs

using System;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using Xrm.Tools.WebAPI;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Xrm.Tools.WebAPI.Results;
using System.Dynamic;
using Xrm.Tools.WebAPI.Requests;
using System.Collections.Generic;

namespace InspectionManagementApp
{
    public static class InspectionRouter
    {
        [FunctionName("InspectionRouter")]
        public static void Run([TimerTrigger("0 0 0 * * *")] TimerInfo myTimer, ILogger log)
        {
            log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
            CRMWebAPI api = GetCRMWebAPI(log).Result;
            dynamic whoami = api.ExecuteFunction("WhoAmI").Result; log.LogInformation($"UserID: {whoami.UserId}");
            var inspections = GetInspections(api).Result;
            var users = GetUsers(api).Result;

            Random rnd = new Random(); int sequenceNumber = rnd.Next(10, 99);
            int currentUserIndex = 0;
            foreach (dynamic inspection in inspections.List)
            {
                log.LogInformation($"Routing inspection {inspection.contoso_name}");
                var inspectionResult = new CRMUpdateResult();
                //Your record assignment would like this. We will not assign records to different users in this lab
                // if (users.List.Count > (currentUserIndex))
                //{
                // dynamic currentUser = users.List[currentUserIndex];
                // inspectionResult = RouteInspection(api, inspection, currentUser.systemuserid.ToString(), sequenceNumber).Result;
                //currentUserIndex++;
                //}
                //We will instead assign inspections to the user you are currently logged in as
                inspectionResult = RouteInspection(api, inspection, whoami.UserId.ToString(), sequenceNumber).Result;

            }

        }

        private static async Task<CRMWebAPI> GetCRMWebAPI(ILogger log)
        {
            var clientID = Environment.GetEnvironmentVariable("cdsclientid", EnvironmentVariableTarget.Process);
            var clientSecret = Environment.GetEnvironmentVariable("cdsclientsecret", EnvironmentVariableTarget.Process);
            var crmBaseUrl = Environment.GetEnvironmentVariable("cdsurl", EnvironmentVariableTarget.Process);
            var crmurl = crmBaseUrl + "/api/data/v9.0/";


            AuthenticationParameters ap = await AuthenticationParameters.CreateFromUrlAsync(new Uri(crmurl));

            var clientcred = new ClientCredential(clientID, clientSecret);
            // CreateFromUrlAsync returns endpoint while AuthenticationContext expects authority
            // workaround is to downgrade adal to v3.19 or to strip the tail
            var auth = ap.Authority.Replace("/oauth2/authorize", "");
            var authContext = new AuthenticationContext(auth);

            var authenticationResult = await authContext.AcquireTokenAsync(crmBaseUrl, clientcred);

            return new CRMWebAPI(crmurl, authenticationResult.AccessToken);
        }

        private static Task<CRMGetListResult<ExpandoObject>> GetInspections(CRMWebAPI api)
        {
            var fetchxml = @"<fetch version=""1.0"" mapping=""logical"" >
  <entity name=""contoso_inspection"" >
  <attribute name=""contoso_inspectionid"" />
  <attribute name=""contoso_name"" />
  <attribute name=""ownerid"" />
  <attribute name=""contoso_inspectiontype"" />
  <attribute name=""contoso_sequence"" />
  <attribute name=""contoso_scheduleddate"" />
  <filter type=""and"" >
  <condition value=""0"" operator=""eq"" attribute=""statecode"" />
  <condition attribute=""contoso_scheduleddate"" operator=""today"" />
  <condition attribute=""statuscode"" operator=""in"" >
  <value>1</value>
  <value>463270000</value>
  </condition>
  </filter>
  </entity>
  </fetch>";


            var inspections = api.GetList("contoso_inspections", QueryOptions: new CRMGetListOptions() { FetchXml = fetchxml });
            return inspections;

        }

        private static Task<CRMGetListResult<ExpandoObject>> GetUsers(CRMWebAPI api)
        {
            var users = api.GetList<ExpandoObject>("systemusers");
            return users;
        }
        private static async Task<CRMUpdateResult> RouteInspection(CRMWebAPI api, dynamic inspection, string userId, int sequenceNumber)
        {
            dynamic updateObject = new ExpandoObject();
            ((IDictionary<string, object>)updateObject).Add("ownerid@odata.bind", "/systemusers(" + userId + ")");
            updateObject.contoso_sequence = sequenceNumber.ToString();
            return await api.Update("contoso_inspections", new Guid(inspection.contoso_inspectionid), updateObject);
        }        
    }
}

**Comment by RobertRybaric** [comment]
The Azure Function does not work, when you do not remove the following line from the fetchxml:

<condition attribute=""contoso_scheduleddate"" operator=""today"" />

With this line, the code will never return any single inspection record.

**Comment by RobertRybaric** [comment]
BTW, now using the updated publisher creation in the maker portal, the generated numerical values from choice columns start with 100.000.000, so the numerical values like 463270000 are wrong as well.

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update for this lab in the next couple of weeks.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
