### ISSUE TITLE
Lab 6

### ISSUE THREAD

**Issue by HammedAbdulazeez** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#20]
# Module: 00
#### Step: 00

Description of issue

Task 1

1. You can not download "PluginBase.cs" file from the github. Please make this available to be downloadable
2. Also in the code, throuwn an error:
        protected override void ExecuteCDSPlugin(LocalPluginContext localcontext)

        {

            base.ExecuteCDSPlugin(localcontext);

            var permitEntity = localcontext.PluginExecutionContext.InputParameters["Target"] as Entity;
            var buildSiteRef = permitEntity["contoso_buildsite"] as EntityReference;
            localcontext.Trace("Primary Entity Id: " + permitEntity.Id);
            localcontext.Trace("Build Site Entity Id: " + buildSiteRef.Id);
            string fetchString = "<fetch output-format='xml-platform' distinct='false' version='1.0' mapping='logical' aggregate='true'><entity name='contoso_permit'><attribute name='contoso_permitid' alias='Count' aggregate='count' /><filter type='and' ><condition attribute='contoso_buildsite' uitype='contoso_buildsite' operator='eq' value='{" + buildSiteRef.Id + "}'/><condition attribute='statuscode' operator='eq' value='463270000'/></filter></entity></fetch>";
            localcontext.Trace("Calling RetrieveMultiple for locked permits");
            var response = localcontext.OrganizationService.RetrieveMultiple(new FetchExpression(fetchString));
            int lockedPermitCount = (int)((AliasedValue)response.Tables[0]["Count"]).Value;
            localcontext.Trace("Locket Permit count : " + lockedPermitCount);
            if (lockedPermitCount > 0)
            {
                throw new InvalidPluginExecutionException("Too many locked permits for build site");
            }

        }
![Capture](https://user-images.githubusercontent.com/57278221/146451149-9fdd744e-ce5e-4954-b0d2-459bba940434.PNG)

any correction?

Repro steps:

1.
1.
1.

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are updating this lab in the next couple of weeks please stay tuned.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
