### ISSUE TITLE
PL-400 Issue

### ISSUE THREAD

**Issue by DanielMcKinney-LODS** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#3]
# Module: All 
#### Step: b (Get the locked Permit Count and throw InvalidPluginExecutionException if the Count is more than 0)

Description of issue: 

The lab instructions are incorrect. 
The following references "tables" and does not generate the correct locker permits count: _int lockedPermitCount = (int)((AliasedValue)response.Tables[0]["Count"]).Value_

![image](https://user-images.githubusercontent.com/62155069/115012046-f5abbd00-9e74-11eb-9520-7183c0adc1d1.png)

It should be:  int lockedPermitCount = (int)((AliasedValue)response.Entities[0]["Count"]).Value;
   
This needs to be corrected as soon as possible.  Thank you!

**Comment by RobertRybaric** [comment]
This was probably caused by a too enthusiastic mass rename of the whole text from "Entities" to "Tables". In fact, in the code, there needs still to be "Entities".

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update for this lab in the next couple of weeks.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
