### ISSUE TITLE
Trail Environment to be mentioned as Prod.

### ISSUE THREAD

**Issue by shalinigupta2501** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#54]
# Module: 01
#### Step: 03 and 04

Description of issue: In the steps, Trial Environment has been mentioned as Dev. However, it needs to be Prod env.

Repro steps:

3. Your Dev environment should now show in the list of Environments.
4. Your environment may take a few minutes to provision. Refresh the page if needed. When your environment is prepared, select your Dev environment by clicking on the ellipses next to its name to expand the drop down menu and select Settings.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by skulthm-ms** [comment]
We don't provide a production environment as part of the lab. We design the course using a trial so its more accessible and we called the environment Dev. Please feel free to bring your own subscription.
