### ISSUE TITLE
Rectify Development environment as Dev only.

### ISSUE THREAD

**Issue by shalinigupta2501** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#55]
# Module: 01
#### Step: 01

Description of issue: Development environment has been mentioned as Prod env.

Repro steps:

1. Create the community plan environment

Navigate to https://powerapps.microsoft.com/en-us/communityplan/
Click on Existing user? Add a dev environment
Enter your credentials when prompted to sign in
Select your country from the dropdown menu and click Accept
Navigate to https://admin.powerplatform.microsoft.com/environments to see a new environment has been created by the system. We will refer to it as "Prod" environment for the rest of this course.

**Comment by skulthm-ms** [comment]
As mentioned in the previous issue, we are renaming these trial accounts for the instructional design purposes only.
