### ISSUE TITLE
Lab 01 - UI has changed, several issues

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#56]
#### Step: Various

Description of issue

This lab has some 'drift' between from what the instructions currently say, vs. what the UI now looks like.  A sampling of issues are noted here:

1. Screenshots out-of-date, in particular where it used to have a 'tabbed' display horizontally, it now appears to have 'tabs' located vertically i.e. this:
 
![image](https://user-images.githubusercontent.com/49700217/188969176-e98f6414-2a0a-4587-a0db-743a607b6b89.png)

Now looks like this:
 
![image](https://user-images.githubusercontent.com/49700217/188969224-f3a7b3e3-0bb3-4e91-a9af-ab1a9e34d97f.png)

2. General UI/text changes - that a user ought to be able to figure out themselves - but nevertheless should be updated at some point to match the updated UI: , i.e. '**+Add Column**' is now '**+New Column**', and '**Select Done**' is now '**Select Save**','Select **Select Components**' is now 'Select **Select Objects**'

3. More serious UI/text changes that are not so clear such as in Exercise 2, Task 1, Step 3 it says 'Select **Required**', however there seems to be a new dropdown with 3 addt'l options from which to choose.  (I am guessing '**Business required**' is desired here?

![image](https://user-images.githubusercontent.com/49700217/188970391-92da1ea0-809e-4cdd-ab6b-9eeb67a1d3fb.png)

Another example in Step 5 is where it says 'Click on chevron icon next to **Default**'/'Select **Custom** for filter.'/'Select **Save Table**', but I am unable to find any '**Default**', **Custom** or other area with such a chevron that allows me to select this option.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by skulthm-ms** [comment]
Thank you. We are aware of the UI changes and unfortunately it changes faster than we can update the content. We have this mentioned in the TrainerPrepGuide. We are logging and triaging these UI mismatches and we will update them as soon as we can.
