### ISSUE TITLE
Errors during Plugin steps

### ISSUE THREAD

**Issue by J-O-S-H-C** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#57]
# Module: 00
#### Step: 00

Description of issue
Getting reports of multiple "Plugin" errors on this Lab.

### Task: 03
![image](https://user-images.githubusercontent.com/39581053/189206151-fabcc760-a024-478d-b069-c2e2ae4c096a.png)
![image](https://user-images.githubusercontent.com/39581053/189206114-10c39c07-68e1-42ea-bac9-1ab6eba65af1.png)

# Lab Number: 6 Plugins
#### Step Number: 5
![image](https://user-images.githubusercontent.com/39581053/189206270-0b6af5c3-9b41-4420-b79d-96031191b4ed.png)

**Comment by DavidPaf** [comment]
Same error message CurrentUserService not found

**Comment by mhykgyver** [comment]
Change it to InitiatingUserService to make this work...

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by skulthm-ms** [comment]
As mhykgyver suggeted, please use InitiatingUserService instead. We updated the instructions. Thank you all for your contributions.
