### ISSUE TITLE
CurrentUserService not found in ILocalPluginContext

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#60]
# Module: 00
#### Step: 04

Description of issue
https://microsoftlearning.github.io/PL-400_Microsoft-Power-Platform-Developer/Instructions/Labs/LAB%5BPL-400%5D_Lab06_Plugins.html

"Build the project and make sure it succeeds. To build the project, right click on the project and select Build. Check the output and make sure that the build has succeeded. If it does not, go back and review your work compared the steps documented here."

Error at 
localPluginContext.CurrentUserService.RetrieveMultiple 

CurrentUserService not found in ILocalPluginContext 

Repro steps:

1.  Follow steps to Build the project.
1.
1.

**Comment by DavidPaf** [comment]
@MoRage  kindly take a look at lab 06

**Comment by DavidPaf** [comment]
Seem we must use Iplugin interface and use organization service reference for web api call, not CurrentUserService

Below is current working solution:
======================


using System.ServiceModel;
using Microsoft.Xrm.Sdk;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Xrm.Sdk.Query;

namespace ContosoPackageProject
{

    public class PreOperationPermitCreate : IPlugin
    {
        public void Execute(IServiceProvider serviceProvider)
        {
            // Obtain the tracing service
            ITracingService tracingService =
            (ITracingService)serviceProvider.GetService(typeof(ITracingService));

            // Obtain the execution context from the service provider.  
            IPluginExecutionContext context = (IPluginExecutionContext)
                serviceProvider.GetService(typeof(IPluginExecutionContext));

            // The InputParameters collection contains all the data passed in the message request.  
            if (context.InputParameters.Contains("Target") &&
                context.InputParameters["Target"] is Entity)
            {
                // Obtain the target entity from the input parameters.  
                Entity entity = (Entity)context.InputParameters["Target"];
                EntityReference buildSiteRef = (EntityReference)entity.Attributes["contoso_buildsite"];


                // Obtain the organization service reference which you will need for  
                // web service calls.  
                IOrganizationServiceFactory serviceFactory =
                    (IOrganizationServiceFactory)serviceProvider.GetService(typeof(IOrganizationServiceFactory));
                IOrganizationService service = serviceFactory.CreateOrganizationService(context.UserId);

                try
                {
                    // Plug-in business logic goes here.  
                    tracingService.Trace("Primary Entity Id: " + entity.Id);
                    tracingService.Trace("Build Site Entity Id: " + buildSiteRef.Id);
                    string fetchString = "<fetch output-format='xml-platform' distinct='false' version='1.0' mapping='logical' aggregate='true'><entity name='contoso_permit'><attribute name='contoso_permitid' alias='Count' aggregate='count' /><filter type='and' ><condition attribute='contoso_buildsite' uitype='contoso_buildsite' operator='eq' value='{" + buildSiteRef.Id + "}'/><condition attribute='statuscode' operator='eq' value='463270000'/></filter></entity></fetch>";
                    tracingService.Trace("Calling RetrieveMultiple for locked permits");
                    var query = new FetchExpression(fetchString);

                    EntityCollection response = service.RetrieveMultiple(query);

                    int lockedPermitCount = (int)((AliasedValue)response.Entities[0]["Count"]).Value;
                    tracingService.Trace("Locket Permit count : " + lockedPermitCount);
                    if (lockedPermitCount > 0)
                    {
                        throw new InvalidPluginExecutionException("Too many locked permits for build site");
                    }

                }

                catch (FaultException<OrganizationServiceFault> ex)
                {
                    throw new InvalidPluginExecutionException("An error occurred in Permit plugin.", ex);
                }

                catch (Exception ex)
                {
                    tracingService.Trace("Permit plugin: {0}", ex.ToString());
                    throw;
                }
            }
        }
    }
}

**Comment by DavidPaf** [comment]
@MoRage kindly update the document as well.

**Comment by arleiribeiro** [comment]
Hello @DavidPaf , I really like your way to onboard the problem, thank you very much to share this.

Moving into the task 02 I'm trying to apply the same method; I'm a bit confuse how to apply this method inside this requirement to override the ExecuteDataversePlugin method.

Following your suggested code actually I'm going to use the parent IPlugin insted of the PluginBase interface (Am I correct?)
in this way I'm not creating a proper ExecuteDataversePlugin to be overwritten;

        protected override void ExecuteDataversePlugin(ILocalPluginContext localPluginContext)


Should I follow the same method, creating a new class named LockPermitCancelInspections with 
LockPermitCancelInspections : IPlugin  
and public void Execute(IServiceProvider serviceProvider), ignoring the overwrite?

Thank you in advance!!

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review solved this issue with pull request #64.

**Comment by skulthm-ms** [comment]
Thank you all for the contributions to keep this repo current. I am closing this as we made the updates.
