### ISSUE TITLE
"npm run build" never succeeds

### ISSUE THREAD

**Issue by peteravila** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#62]
# Module: 00
#### Step: 7

Description of issue
"npm run build" generates errors. I've tried it on three different instances of the lab and am certain that I am performing every step to the letter. 

Repro steps:

1. I follow all the stsps in Tasks 1 and 2 up to Task 2 Step 7.
2. At step 7, I run the specified command: npm run build
3. The result is always as shown in the image below:

![image](https://user-images.githubusercontent.com/42875531/206327529-f4081e13-2d6c-426b-87db-96c6d67fce0c.png)

**Comment by JonFjolnirAlbertsson** [comment]
I got the same error.

**Comment by peteravila** [comment]
Hi, Jon :-) Thanks for adding your voice! 

I'm suspecting two things: 1) It seems that when the lab instructions were written, Node.js 14.X was used. Today's version is a bit higher than that. Could it be a versions issue? There are so many components that work together. What Happens when one of them upgrades into something that generates errors? I tried to download and install 14.X, but it errored out during the installation. 2) The other thing is that the problem might be in some new dependency that was added after the lab was written. 

Let's hope someone can clairfy this for us soon. Thanks again!

**Comment by mhykgyver** [comment]
Hi all,

Just had this problem with this lab and we managed to fix it:

just modify your .eslintrc.json and include the rules as follows:

"rules": {
      "no-unused-vars": "off",
      "no-undef" : "off"
    }

and that should fix the problem...enjoy!!!

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by julians1966** [comment]
I experienced this issue. The solution provided by @mhykgyver solves the problem

**Comment by skulthm-ms** [comment]
Thank you all for contributing here. I can added a note to the content in case of an error.

**Comment by peteravila** [comment]
> I am trying to implement Mhykgyver's solution, but I have several files called .eslintrc.json on my computer and so far none of them have worked. 1) Can you please tell me which .eslintrc.json file I need to change, and 2) once the change is made to the correct file, do I just save it and that's it, or do I have to restart/reinitiate/recompile/other... anything?

Thank you!

**Comment by peteravila** [comment]
Please disregard my last. I see what I did wrong. The solution is working! Thank you
