### ISSUE TITLE
Labs - all

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#63]
# Module: 00
#### Step: 00

Description of issue
Here is the problem.
Can I ask, who is maintaining the labs?
Lab06 is out of date and has no way of working unless a trainer writes the whole thing.
Lab05 has issues with node and more issues.
How does anyone cover a good of high quality.
I shall do my best based on the effort Microsoft are applying to the course material.
Repro steps:

1.
1.
1.

**Comment by skulthm-ms** [comment]
Thank you for the feedback. We made some updates, please let us know if these aren't working for you by filing a specific issue.
