### ISSUE TITLE
Lab 07 :  Lab 07 – Azure Functions

### ISSUE THREAD

**Issue by Sharmajivibhor** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#65]
# Module: 10
#### Step: 04

Description of issue : The nugget package Microsoft.IdentityModel.Clients.ActiveDirectory. is deprecated.  

Due to this complete code need to change. 

Repro steps:

1.
1.
1.

**Comment by skulthm-ms** [comment]
Thank you Sharmajivibhor, we will look into it.

**Comment by DanePillay-nel** [comment]
Lab worked fine this past week. No Changes were made.
I have a link to my code on my blog.
I updated the reference to the status reason field.

https://thatsolutionsguy.wordpress.com/2021/07/15/pl-400-module-7-azure-function-source-code/

**Comment by skulthm-ms** [comment]
The lab should still work. however, we are actively working on refreshing the lab and course content.
