### ISSUE TITLE
XRM doesn't register new assembly

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#66]
#### Step: 04

After downloading the XRM Tools and extracting them, I'm able to launch the PluginRegistration application and log in using the Tenant credentials. But after logging in and selecting "Register New Assembly" from the "Register" drop down list, the PluginRegistration app stops functioning. No errors are received and the application itself never crashed, it just won't respond to any of the options in the "Register" drop down list. This error seems to be intermittent, only a portion of the class were affected.

**Comment by skulthm-ms** [comment]
Thank you AMoring8787, we will look into it.

**Comment by frksn** [comment]
The file or dependencies are blocked. dir -recurse | unblock-file.
Depends on where the zip is downloaded (in downloads or elsewhere)

**Comment by AMorin8787** [comment]
There are instructions to unblock the files. The issue still occurs regardless of being unblocked and/or current directory.

**Comment by julians1966** [comment]
I don't use the XRM Tools, I download the tools from nuget - see https://learn.microsoft.com/en-us/power-apps/developer/data-platform/download-tools-nuget

**Comment by julians1966** [comment]
See https://learn.microsoft.com/en-us/training/modules/use-developer-tools-extend/2-exercise 
I walk students through this and use the Plugin Registration Tool from this rather than Xrm.Tools in the labs

**Comment by skulthm-ms** [comment]
We couldn't reproduce this, as you mentioned, this might be intermittent issue. But we will update the instructions soon to reflect the Plugin Registration Tool instead of Xrm.
