### ISSUE TITLE
Lab 04 Ribbon Workbench

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#7]
# Module: 04
#### Step: 02: Load the Permit Management solution

Description of issue

After selection Permit Management solution the following warning appears: 

• The solution contains Entities that have all their sub-components included.
• The solution contains non-entity components (e.g. attributes/forms/apps/dashboards/workflows).
• There are more than 5 entities in the solution.
Please create a solution and add only the Entities you wish to edit, with no sub-components!

**Comment by KrypticChewie** [comment]
I had this issue when starting lab 4 after importing the completed solution for lab 3.  Did you go through all the labs and have this issue? @rramoscabral

**Comment by RobertRybaric** [comment]
That is a known issue with the Ribbon Workbench. You need to create a separate solution and include only the naked "Permit" table into this solution and use it for the Ribbon Workbench

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update for this lab in the next couple of weeks.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
