### ISSUE TITLE
PL-400 Labs general comments

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#70]
My view on the course is that it its purpose is to

a)	Understand all the different methods by which the platform can be extended and for each of these
i.	their capabilities
ii.	their limitations
iii.	where they run (client side or back-end)
iv.	how they run (synchronous or asynchronous)
b)	Know how to start developing with each method i.e. the tools required and code starting points

The course objective should be for students to be able to select the correct method to meet a requirement. 

Note: I do not use the Exercises in Learn/Slides as these duplicate these GitHub labs.

As for the labs, the ones that are there are good (some fixes are required) and help the students meet the course purposes above. However, there are labs missing for:
•	Module 3 Master advance techniques and data options in canvas apps
•	Module 4 Automate a business process using Power Automate
•	Module 5 Introduction to developing with Power Platform

One issue I have with the lab steps is that the copy and paste of each statement is very difficult to get right and many students end up spending ages trying to figure out where they made an error in copy/paste. I provide the completed code to students – these should be added to GitHub.

One key point is the labs build on each other and must be done in the numbered order, but the slides/modules do not reflect this order and I deliver module 6 (Extending the Power Platform Dataverse) _after_ modules 7 (Extending the Power Platform user experience Model Driven apps) and 8 (Create components with Power Apps Component Framework).

**Comment by skulthm-ms** [comment]
Thank you for providing this valuable feedback summary. Its timely since we are actively working on refreshing the content. We will do our best to incorporate all of your feedback.
