### ISSUE TITLE
Lab 10 ALM Script task fails - ERROR:src refspec main does not match any

### ISSUE THREAD

**Issue by DanePillay-nel** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#73]
# Module: 10
#### Step: 12

Description of issue
The script fails with ERROR:src refspec main does not match any

Solution so far is simple. Include git fetch after line 3.

  echo commit all changes
  git config user.email "user@myorg.onmicrosoft.com"
  git config user.name "Automatic Build"
git fetch
  git checkout main
  git add --all
  git commit -m "solution init"
  echo push code to new repo
  git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin main

**Comment by ngeorgeault** [comment]
I can confirm.
I was able to reproduce the issue.
Same error on my side and "git fetch" worked for me.

**Comment by julians1966** [comment]
The ALM lab is being removed at the next update
The lab in out of date and uses classic pipleines not YAML

**Comment by julians1966** [comment]
ALM lab has been removed.

**Comment by DanePillay-nel** [comment]
Wow, thanks for the heads up

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
