### ISSUE TITLE
Lab 0: Ex 2: Unable to establish PowerPlatform Trial! : Entire class is dead in the water

### ISSUE THREAD

**Issue by peteravila** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#78]
# Lab 0
#### Step 7 - expand **Billing** and select **Purchase services**.

Purchase services does not exist and none of the other options seem to provide the functionality of the old Purchase services option. As a result, I cannot register the credential. That means students cannot access the Power Platform environment! Class starts Monday btw. Is there no one at MS coordinating changes to training materials?

**Comment by julians1966** [comment]
Which Lab hoster are you using? Just been into the lab in godeploy and I can see Purchase Services:
![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/29278645/52406aee-782f-4854-9789-c64de9f7e321)

Workaround is to go to https://www.powerapps.com/ and start a free trial and sign in with the Microsoft 365 credentials in your lab

**Comment by julians1966** [comment]
I've just checked PL-200 lab, Purchase services has been removed. Looks like someone has locked down the tenants used for labs. You need to escalate this with your lab hoster

**Comment by julians1966** [comment]
I have raised with the lab hoster I use and I will raise a PR on GitHub as well

**Comment by julians1966** [comment]
Workaround steps

1. Navigate to https://powerapps.microsoft.com and click Start free.
2. Under Work email, enter Microsoft 365 email address for the lab in the text box below Enter your email to start your free trial, check the agreement box, and click Start your free trial.
3. Enter the Microsoft 365 password for the lab if prompted and click Sign in.
4. Select Yes to stay signed in?
5. Enter 1234567890 into the Phone Number field.
6. Navigate to https://admin.microsoft.com.

Note: When adding licenses use Power Apps Plan 2 Trial instead of  Power Apps per user plan

**Comment by peteravila** [comment]
Thanks for the replies! Will attempt Julian's workaround shortly ad report back. Lab hoster is Skillable/Learn on Demand.

**Comment by peteravila** [comment]
Julian, about the workaround you're suggesting, It sounds like that used to be the "normal" approach until recently. If that's the case, and if I recall correctly, only one environment can be created that way. The PL-400 course requires two environments. I'm afraid of going that route and "burning up" my credential. To get another credential, I'd have to end my lab and start a new one (I'm opening the lab throu "Courses" in Skjillable/Learn on Demand to prep. I open the lab in Classes to teach the live class, and I'm not sure if I can end that lab and create a new one with new credentials if I go that route.) . Can you or anyone confirmm if going through your workaround, I will be able to create those two environments?

**Comment by julians1966** [comment]
You can only create 1 trial environment but you can now create up to 3 Developer environments now in the Power Platform Admin center

You need two environments for the labs and you should create two environments of type Developer

**Comment by peteravila** [comment]
Got it! Thx for the quick reply!! Will try that now...

**Comment by julians1966** [comment]
There is an outstanding PR from me which fixes many of the later lab issues- you can view my lab sets at https://julians1966.github.io/PL-400_Microsoft-Power-Platform-Developer/

**Comment by julians1966** [comment]
I also have created the completed code segments and solutions in my PR - you can see those under https://github.com/julians1966/PL-400_Microsoft-Power-Platform-Developer/tree/master/Allfiles/Labs

**Comment by peteravila** [comment]
Julian--

It never asked me for the password (your step 3, above). It just put me directly into make.powerapps.com! I'm going to attempt to make the environments unless this raises some red flag to you...?

**Comment by peteravila** [comment]
Or should I stop here and use godeploy to register the credentials then return to Skillablle/Learn on Demand?

**Comment by julians1966** [comment]
If you were already signed into Microsoft 365 admin center or Power Apps, you will not be prompted for your password

**Comment by peteravila** [comment]
Understood, Thank you!

**Comment by peteravila** [comment]
Thanks for the workaround!

BTW, purchase services is not coming up on GoDeploy, either

**Comment by peteravila** [comment]
Julian

I am now in class, I am able to use the workaround for all students but one who does not have the "Purchase services" option under billing and also does not see a Trial 2 license when using your workaround. I'm hoping you have a workaround for this situation, too? Thanks!

**Comment by julians1966** [comment]
Have they clicked Start free? Get them to sign out of everything in the browser and clear the cache and try again to sign up for a trial
It could just be cacheing

**Comment by julians1966** [comment]
I have had feedback from go deploy that some tenants have Purchase services and some don't

**Comment by julians1966** [comment]
If still doesn't work get them to end the lab and start the lab again as this should give them a different tenant

**Comment by julians1966** [comment]
If still doesn't work get them to end the lab and start the lab again as this should give them a new different tenant. After that you need to contact your Lab Hoster support

**Comment by peteravila** [comment]
It worked Julian

**Comment by peteravila** [comment]
Thank you!

**Comment by peteravila** [comment]
Thank  you for all your help, Julian

Peter

**Comment by kmtrading** [comment]
For tenants who do not have the "Purchase services" option, you have to go to Marketplace, just above.

**Comment by DanePillay-nel** [comment]
So follow the usual steps of clicking the start free button (old way) to get your subscription working. Then in the admin center choose the new developer option for type of environment and it allows two environments to be created.
