### ISSUE TITLE
Lab 9 - Power Apps Component Framework

### ISSUE THREAD

**Issue by fuau** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#79]
# Module: 09 Power Component Frameworks

### Task: 1.2 & 2.1
Suggestion to do this as well to run properly

Description of issue

Repro steps:

1. Open solution.cdsproj from Solution folder and update the path
<OutputPath>bin/debug</OutputPath>
Ex 2 - Task 2.1 - <Environment URL> with https

**Comment by julians1966** [comment]
This is already included in the PR I raised
Add the following tag to the PropertyGroup
<OutputPath>bin/debug</OutputPath>

**Comment by julians1966** [comment]
Addressed by PR #77 https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/pull/77
