### ISSUE TITLE
Lab 09 Issue with npm run build

### ISSUE THREAD

**Issue by J0eGos** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#82]
#### Step: 11

Description of issue:
Encountering the below issues when attempting to run "npm run build": 
[pcf-1014] [Error] Manifest validation problem: instance.manifest.control[0].resources[0] is not allowed to have the additional property "_"

I have repeated all steps twice and also used the completed forms provided in the latest pull request and still encountering this issue. Any help would be greatly appreciated.

![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/128402777/e1484461-0c2b-498e-bd4b-77423e6706af)

**Comment by DanePillay-nel** [comment]
Hello,

I tried **`npm audit fix --force`**  and then **`npm run build`**  about two or three times and it build the code sucessfully.

Let me know if this works.

**Comment by julians1966** [comment]
Have retested the lab and could not reproduce the error and as had no response I am closing

**Comment by saquibshera** [comment]
I fixed it..
Just update ur manifest file with this one
<?xml version="1.0" encoding="utf-8" ?><manifest>  <control namespace="contoso" constructor="timelinecontrol" version="0.0.1" display-name-key="timelinecontrol" description-key="timelinecontrol description" control-type="standard">        <external-service-usage enabled="false">                </external-service-usage>
        <data-set name="timelineDataSet" display-name-key="Dataset_Display_Key">                      </data-set>    <resources>            <code path="index.ts" order="1"/>                  <css path="css/timelinecontrol.css" order="1" />      <css path="..\node_modules\vis-timeline\dist\vis-timeline-graph2d.min.css" order="2" />                </resources>          </control></manifest>
    


//You need to replace the require statement with an import statement. Here's how you can resolve this issue
//use only  these imports in the  index.ts file.
import { IInputs, IOutputs } from "./generated/ManifestTypes";
import DataSetInterfaces = ComponentFramework.PropertyHelper.DataSetApi;
import { Timeline } from "vis-timeline/standalone";
import * as visTimeline from 'vis-timeline';

Done run npm run build...it will fix

Additionally if not fixed:
pac install latest you can run before the above steps.
