### ISSUE TITLE
PL-400 Trainer Materials/foils

### ISSUE THREAD

**Issue by Mindbl2000** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#83]
# Module: All
#### Step: All

Description of issue

Repro steps:

I try to find the course material and foils for MCTs. I can see the Instructions and the Labs and Solutions, but no foils!

Where can I get this and if necessary, further course materials for MCTs?

b. rgds.
Petra

**Comment by julians1966** [comment]
What do you mean by foils? Do you mean the courseware and slides?

Slides are on the Learning Download Center. Along with the slides you will find the change log and trainer prep guide. The trainer prep guide contains the modules on Microsoft Learn that are used as the courseware

**Comment by julians1966** [comment]
Closing as no response
