### ISSUE TITLE
Lab 10 - Plugin

### ISSUE THREAD

**Issue by kmtrading** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#84]
# Module: 10 Plugins
#### Step: 2

There is a typo in this line and it is not needed, I suggest removing it:

using ContosoPackagePoject;

**Comment by julians1966** [comment]
This has been resolved in my latest PR

**Comment by ephiax20** [comment]
Resolved by #77 - Due to be merged very soon I hope.

**Comment by julians1966** [comment]
Should be by the end of this week to coincide with release of latest course materials
