### ISSUE TITLE
Multiple errors in Learning Paths 0 and 10

### ISSUE THREAD

**Issue by brookbeckertesting** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#86]
# Learning Paths: 00, 10
#### Step: 10 (LP 0), Step 1, part 6 (LP 10)

Description of issue

Repro steps:

1. LP 0, Exercise 02, Task 02, Step 10: The instruction to acquire a PowerApps per user plan isn't available in the Admin environment in Lab 0, 

![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/94069201/c7a9fd10-1511-4dec-9be6-63e5ef65f118)

![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/94069201/8b9827a4-ac8c-4d08-9872-726e6ab572e9)

2. LP 10, Exercise 3, Task 3.2, Step 1, part 6: The status reason value on the Test Permit after completing the prerequisite steps should be set to Status Reason Value locked, but it's set to Active.

![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/94069201/6a7ae26c-ccec-4335-a5f4-4fb7704ff25e)

**Comment by julians1966** [comment]
Lab 0: Looks like Power Apps per user plan license has been replaced by Power Apps Premium
Will update the lab step
Lab 10: The status reason for the Test Permit should be changed to locked after clicking the lock permit button. Check your code and the trace log
