### ISSUE TITLE
Outdated .Net Version

### ISSUE THREAD

**Issue by adntobias** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#88]
# Module: 10
#### Step: 01

Description of issue
The instructions refer to .Net 3. This version has not been supported by Azure for a long time and should be upgraded to .Net 6.
At the same time, Lab providers should no longer use Visual Studio 2019, but Visual Studio 2022, otherwise .Net 6 will not be supported.

The same applies to all other labs that rely on .Net 3 and Visual Studio 2019.

**Comment by julians1966** [comment]
Also need to update from using MDAL to MSAL as MDAL is deprecated
This is the only lab that refers to .NET 3 and all the rest are .NET 6 (LTS), or still .NET Framework for plugins 
The main issue is the use of Xrm.Tools.CrmWebAPI that hasn;t been updated in a long time. Need to replace the use of this helper.

**Comment by julians1966** [comment]
Waiting for new VM with Windows 11 before can update .NET and Visual Studio

**Comment by ephiax20** [comment]
New VM is on the way, we're working with Skillable on this now.

**Comment by julians1966** [comment]
Any update on the new VM?

**Comment by geschwei** [comment]
Hi Everyone, The VM will be deployed to this course by early Feb. Thank you for your patience.
