### ISSUE TITLE
Ribbon Workbench : for performance reasons, this solution cannot be loaded.

### ISSUE THREAD

**Issue by vatanjoshi** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#9]
# Module: 04
##### Step: 02 - Load the Permit Management solution

Description of issue: I do see "Permit Management" solution in the pop-up opened for selecting the Load Solution but when I click "OK" it shows a message "for performance reasons, this solution cannot be loaded...". I have followed the instructions twice now, but couldn't resolve the issue.

![image](https://user-images.githubusercontent.com/17869959/123902429-7d8c6800-d98a-11eb-981e-8d7352f56070.png)

![image](https://user-images.githubusercontent.com/17869959/123902379-68afd480-d98a-11eb-9c16-28062a92fa8f.png)

Following entities are in Permit Management Solution:
![image](https://user-images.githubusercontent.com/17869959/123902706-f095de80-d98a-11eb-8a36-3faed30482c3.png)

**Comment by RobertRybaric** [comment]
That is a known issue with the Ribbon Workbench. You need to create a separate solution and include only the naked "Permit" table into this solution and use it for the Ribbon Workbench

**Comment by DanePillay-nel** [comment]
Add the Permit table only to the default solution and open that instead.

**Comment by skulthm-ms** [comment]
Thank you for reporting this. We are releasing an update for this lab in the next couple of weeks.

**Comment by skulthm-ms** [comment]
Thank you again for the feedback, we just updated the lab and these issues should be resolved. Please continue to support us by reporting any issues you may find.
