### ISSUE TITLE
Minor type-o in Lab 3 - Canvas App

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#91]
# Lab: 3
## Exercise: 2

Description of issue:

Just a minor type-o.   Exercise #2 has Task 2.1, Task 2.2, and Task 2.4.   Task 2.4 should be renamed to Task 2.3.

**Comment by julians1966** [comment]
Agreed. WIll fix
