### ISSUE TITLE
 **Ask in PowerApps** dynamic content in Step 3 is missing 

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#93]
# Module: 05
#### Step: 3

**Description of issue:**  Powerapps trigger  is now Powerapps(v2).  When following the steps, **Ask in PowerApps** dynamic content in Step 3 is missing

Repro steps:

follow the steps for Exercise 2, Task 2.1

**Comment by julians1966** [comment]
Need to change steps and screenshot for PowerApps (V2) connector

Need to add an input to the trigger step instead of using Ask in PowerApps
