### ISSUE TITLE
No Owner column on Permit Type table

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#94]
# Learning Path:  2
#### Step: 7

Description of issue

The Permit Type table was created as an Organizational Owned table and does not have an owner field. 
The step says "Add Require Inspections and Require Size columns to the form between Name and Owner."

The step should say "Add Require Inspections and Require Size columns to the form below Name"
The screenshot needs to be updated to not show the Owner

**Comment by zixuansunnydeng** [comment]
I face the same issues
