### ISSUE TITLE
Power Platform Trial Requires Credit Card

### ISSUE THREAD

**Issue by esarikaya** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#97]
# Module: 01
#### Step: 12

When you click "Try now"  to activate the Power Apps Premium free trial, the Information Required dialog box pops up. It states "In order to start your trial subscription, we require a credit card payment method to be added to your account. This payment method will not be charged without your consent. After it is added, please retry activating your trial." The only option is the "Continue" button that takes you directly to the Payments Methods page.

These tenants are Microsoft property, I don't think that it is proper to ask students to provide their personal credit card information to the tenants that are owned by Microsoft.

Thanks for any help.

**Comment by julians1966** [comment]
I noticed at the weekend that trials now require a credit card
This is a major issue for all Power Platform courses that use trials

**Comment by julians1966** [comment]
Workaround is to create a developer environment which should not require a license

**Comment by julians1966** [comment]
I have just tested on Skillable and Language and Currency are available, and I can create Developer environments without starting a trial

**Comment by ephiax20** [comment]
@esarikaya I have got a ticket open with MS Support about the Language and Currency drop-downs being blank. I have replicated that issue with the MS Support engineers. Ref: #2310160040003961
