### ISSUE TITLE
Developer Environment Cannot Be Created

### ISSUE THREAD

**Issue by esarikaya** [MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer#98]
# Module: 01
#### Step: 8

Add Dataverse tab, which requires you to pick a language and currency. But neither dropdown boxes are getting populated correctly nor does it allow you to provide input. The save button remains greyed out.

**Comment by julians1966** [comment]
Reopened as need to change lab instuctions to not use a trial
Need to test that this has no impact on the rest of the labs

**Comment by julians1966** [comment]
Sorry reopened in erro - wrong issue

**Comment by ephiax20** [comment]
@esarikaya I have got a ticket open with MS Support about this. I have replicated this issue with the MS Support engineers. The workaround is to refresh the page but it should load the values, hopefully they can fix it.  Ref: #2310160040003961

![image](https://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer/assets/116392278/75cdb171-8874-44da-a934-689ec6b544c0)
